// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE1fg1PAGfWucrWhIOGXsl7_Ad5Bmn7vk',
    appId: '1:981356525153:web:54b6e35261c757f7f65c20',
    messagingSenderId: '981356525153',
    projectId: 'echonote-8787f',
    authDomain: 'echonote-8787f.firebaseapp.com',
    storageBucket: 'echonote-8787f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRimdNJgMxW_74cwosz-n5isRA-Oe0Qw',
    appId: '1:981356525153:android:9e57759047ff5cfef65c20',
    messagingSenderId: '981356525153',
    projectId: 'echonote-8787f',
    storageBucket: 'echonote-8787f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY431I2CTdm0QEZJwJMsUQ3R25FM1xG3I',
    appId: '1:981356525153:ios:f39677deb0463bcbf65c20',
    messagingSenderId: '981356525153',
    projectId: 'echonote-8787f',
    storageBucket: 'echonote-8787f.firebasestorage.app',
    iosBundleId: 'com.example.echonoteclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY431I2CTdm0QEZJwJMsUQ3R25FM1xG3I',
    appId: '1:981356525153:ios:f39677deb0463bcbf65c20',
    messagingSenderId: '981356525153',
    projectId: 'echonote-8787f',
    storageBucket: 'echonote-8787f.firebasestorage.app',
    iosBundleId: 'com.example.echonoteclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE1fg1PAGfWucrWhIOGXsl7_Ad5Bmn7vk',
    appId: '1:981356525153:web:df5f93ccb100f6a9f65c20',
    messagingSenderId: '981356525153',
    projectId: 'echonote-8787f',
    authDomain: 'echonote-8787f.firebaseapp.com',
    storageBucket: 'echonote-8787f.firebasestorage.app',
  );
}
